project_name: rewrite-inplace
dist: build

before:
  hooks:
    - go mod download

builds:
  - binary: rewrite-inplace
    main: main.go
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    flags:
      - -trimpath
    hooks:
      post:
        - /bin/sh -c "upx -q '{{.Path}}' || true"
    goos:
      - aix
      - android
      - darwin
      - dragonfly
      - freebsd
      - illumos
      - js
      - linux
      - netbsd
      - openbsd
      - plan9
      - solaris
    goarch:
      - 386
      - amd64
      - arm
      - arm64
      - ppc64
      - ppc64le
      - mips
      - mipsle
      - mips64
      - mips64le
      - riscv64
      - s390x
      - wasm
    goarm:
      - 5
      - 6
      - 7
    gomips:
      - hardfloat
      - softfloat

archives:
  - format: binary

checksum:
  algorithm: sha512
